routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('toDoTask','ToDoTaskController');
Route::get('/','ToDoTaskController@index');
/*Route::get('/', function () {
    return view('welcome');
});*/

app/ToDoTask.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ToDoTask extends Model
{
    protected $table = 'to_do_tasks';
    protected $fillable = ['id','name','description','created_at','updated_at'];

    public static function boot() {
        parent::boot();
        static::deleting(function($toDoTask) { // before delete() method call this
            ToDoMirror::find($toDoTask->id)
                ->delete();
        });
        self::created(function($toDoTask){
            ToDoMirror::create($toDoTask->toArray());
        });
        self::updated(function($toDoTask){
            $toDoMirror = ToDoMirror::find($toDoTask->id);
            $toDoMirror->update($toDoTask->toArray());
        });
    }
}

app/Http/Controllers/Api/ToDoTaskController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\ToDoTaskRequest;
use App\Http\Resources\ToDoTask as ToDoTaskResource;

use App\ToDoMirror;
use App\ToDoTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;

class ToDoTaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(
            ['toDoTasks'=>ToDoTask::all()]
        );
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ToDoTaskRequest $request)
    {
        $toDoTask = ToDoTask::create($request->all());
        return response()->json([
            'message'=>'To Do task created successfully',
            'data'=>$toDoTask
        ],201);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function show(ToDoTask $toDoTask)
    {
        return response()->json([
            'message'=>'To Do task updated successfully',
            'data'=>$toDoTask
        ],200);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function update(ToDoTaskRequest $request, ToDoTask $toDoTask)
    {
        $toDoTask->update($request->all());
        return response()->json([
            'message'=>'To Do task updated successfully',
            'data'=>$toDoTask
        ],200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function destroy(ToDoTask $toDoTask)
    {
        $toDoTask->delete();
        return response()->json([
            'message'=>'Task deleted successfully',
        ],200);
    }
}

app/Http/Controllers/ToDoTaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ToDoTaskRequest;
use App\Http\Resources\ToDoTask as ToDoTaskResource;

use App\ToDoTask;
use Illuminate\Support\Facades\Session;

class ToDoTaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('toDoTask.index')
            ->with('toDoTasks',ToDoTask::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('toDoTask.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ToDoTaskRequest $request)
    {
        ToDoTask::create($request->all());
        Session::flash('success','ToDo task created successfully');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function show(ToDoTask $toDoTask)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function edit(ToDoTask $toDoTask)
    {
        return view('toDoTask.index')
            ->with('toDoTask',$toDoTask)
            ->with('toDoTasks',ToDoTask::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function update(ToDoTaskRequest $request, ToDoTask $toDoTask)
    {
        $toDoTask->update($request->all());
        Session::flash('info','ToDo task created successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ToDoTask  $toDoTask
     * @return \Illuminate\Http\Response
     */
    public function destroy(ToDoTask $toDoTask)
    {
        $toDoTask->delete();
        Session::flash('error','ToDo task deleted successfully');
        return redirect()->back();
    }
}

resources/views/toDoTask/form.blade.php
<form action="{{route('toDoTask.store')}}" method="post">
    {{csrf_field()}}
    <div class="form-group row">
        <div class="col-12">
            <p class="text-left addTaskTitle">
                Add A Task
            </p>
        </div>
    </div>
    <div class="form-group row">
        <label for="name"
               class="col-sm-12">Name</label>
        <div class="col-sm-12">
            <input type="text"
                   class="form-control"
                   value="{{old('name')}}"
                   id="name" name="name" placeholder="name">
            @error('name')
            <div class="error_form text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="description"
               class="col-sm-12">Description</label>
        <div class="col-sm-12">
                        <textarea
                                class="form-control"
                                id="description"
                                name="description"
                                placeholder="description">{{old('description')}}</textarea>
            @error('description')
            <div class="error_form text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12 text-center">
            <input type="submit" class="btn btn-primary submit-btn" value="Add">
        </div>
    </div>
</form>

resources/views/toDoTask/formUpdate.blade.php
<form action="{{route('toDoTask.update',[$toDoTask->id])}}" method="post">
    {{csrf_field()}}
    {{method_field('PUT')}}
    <div class="form-group row">
        <div class="col-8">
            <p class="text-left addTaskTitle">
                Update Task
            </p>
        </div>
        <div class="col-4">
            <a href="{{route('toDoTask.index')}}" class="btn btn-success">
                Create new task
            </a>
        </div>
    </div>
    <div class="form-group row">
        <label for="name"
               class="col-sm-12">Name</label>
        <div class="col-sm-12">
            <input type="text"
                   class="form-control"
                   value="{{!empty(old('name'))?old('name'):$toDoTask->name}}"
                   id="name" name="name" placeholder="name">
            @error('name')
            <div class="error_form text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="description"
               class="col-sm-12">Description</label>
        <div class="col-sm-12">
                        <textarea
                                class="form-control"
                                id="description"
                                name="description"
                                placeholder="description">{{!empty(old('description'))?old('description'):$toDoTask->description}}</textarea>
            @error('description')
            <div class="error_form text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12 text-center">
            <input type="submit" class="btn btn-primary submit-btn" value="Update">
        </div>
    </div>
</form>

resources/views/toDoTask/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6">
            @if(isset($toDoTask))
                @include('toDoTask.formUpdate')
            @else
                @include('toDoTask.form')
            @endif
        </div>
        <div class="col-md-6">
            @include('toDoTask.previousTasks')
        </div>
    </div>
@endsection

resources/views/toDoTask/previousTasks.blade.php
@if(!empty($toDoTasks))
<div class="row padding-30">
    <div class="col-12 previous-tasks-header">
        <p>
        To Do Tasks
        </p>
    </div>

    <div class="col-12 background-white to-do-tasks-lists ">
        @foreach($toDoTasks as $toDoTask)
            <div class="border-bottom-1 row">
            <div class="col-6 text-left">
                #{{$toDoTask->id}}
            </div>
                <div class="col-6 text-right">
                    <a href="{{route('toDoTask.destroy',[$toDoTask->id])}}"
                       onclick="event.preventDefault();
                                                     document.getElementById('destroy-form').submit();"
                    >
                    <i class="fa fa-trash text-danger" aria-hidden="true"></i>
                        <form id="destroy-form" action="{{ route('toDoTask.destroy',[$toDoTask->id]) }}"
                              method="POST" style="display: none;">
                            {{method_field('delete')}}
                            @csrf
                        </form>
                    </a>
                    <a href="{{route('toDoTask.edit',[$toDoTask->id])}}">
                    <i class="fas fa-pencil-alt text-primary" aria-hidden="true"></i>
                    </a>
                </div>
            <div class="col-12 text-left font-size-20">
                {{$toDoTask->name}}
            </div>
            <div class="col-12 text-left">
                {{$toDoTask->description}}
            </div>
            </div>
        @endforeach
    </div>
</div>
@endif